name: Run Mobile Tests Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Verificar o código no repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar ambiente de testes
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y adb  # Para conectar dispositivos Android
          curl -sSL https://robin.cloud/install.sh | bash
          export PATH="$PATH:/home/runner/.robin"

      # Instalar emulador ou iniciar dispositivo
      - name: Start Android Emulator
        run: |
          sdkmanager "system-images;android-30;google_apis;x86_64"
          avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64"
          nohup emulator -avd test_emulator -no-window -no-audio &

      # Executar os testes localmente
      - name: Run tests locally
        run: |
          robin test run --config ios-flow.yaml --local --app app_qafood.apk