name: Run Android Tests Locally

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Verificar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar dependências do Android SDK
      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # Baixar e instalar o Android Command Line Tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          # Configurar variáveis de ambiente
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH" >> $GITHUB_ENV

      # 3. Instalar pacotes necessários do Android SDK
      - name: Install Android SDK Packages
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          PATH: ${{ env.PATH }}
        run: |
          sdkmanager "platform-tools" "emulator" "platforms;android-30" "system-images;android-30;google_apis;x86_64"
          echo "y" | sdkmanager --licenses

      # 4. Criar e iniciar o emulador Android
      - name: Start Android Emulator
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          PATH: ${{ env.PATH }}
        run: |
          avdmanager create avd -n test_emulator -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          nohup emulator -avd test_emulator -no-window -no-audio &

      # 5. Esperar que o emulador esteja pronto
      - name: Wait for Emulator to Start
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      # 6. Executar os testes
      - name: Run Tests
        run: |
          robin test run --config ios-flow.yaml --local --app app_qafood.apk